server:
  compression:
   enabled: true
logging:
  path: /var/www/logs
  config: classpath:logback-spring.xml
spring:
  output:
    ansi:
      enabled: DETECT
  mail:
    host: smtp.163.com
    username: lkg61230413@163.com
    password: ###
    from: GG<lkg61230413@163.com>
    template-path: classpath:/templates/email/
    properties:mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
      debug: true
  datasource:
    url: jdbc:mysql://ss.itaobao.pub:3306/lore-test?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat,config,wall,slf4j
   # validation-query: SELECT 1
    min-idle: 10
    max-active: 20
    driverClassName: com.mysql.jdbc.Driver
    druid:
      logSlowSql: false
      mergeSql: true
      slowSqlMillis: 3000
      web-stat-filter:
        url-pattern: "/admin/druid/*"
      stat-view-servlet:
        url-pattern : "/admin/druid/*"
        login-username: admin
        login-password: #####
        allow:
        deny:
  jpa:
  # Specify the DBMS
    database: MYSQL
  # Show or not log for each sql query
    show-sql: true
    open-in-view: true
    hibernate:
     show_sql: true
     format_sql: true
     # Hibernate ddl auto (create, create-drop, update)
     ddl-auto: none
     # Naming strategy
     naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     # stripped before adding them to the entity manager)
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
       enable_lazy_load_no_trans: true
  data:
    elasticsearch:
      cluster-name: elasticsearch #节点名字，默认elasticsearch
      cluster-nodes: 127.0.0.1:9200 #节点地址，多个节点用逗号隔开
      local: false
      repositories:
        enable: true
      properties:
        path:
          logs: ./var/log/elasticsearch #elasticsearch日志存储目录
          data: /var/elasticsearch/data #elasticsearch数据存储目录
jodconverter:
  local:
    enabled: true
    office-home: ${pom.office.home} # 设置LibreOffice主目录
    portNumbers: 8100,8101,8102,8103 # 开启多个LibreOffice进程，每个端口对应一个进程
    maxTasksPerProcess: 100 # LibreOffice进程重启前的最大进程数
prod:
  oss:
   accessKeyId:
   secretAccessKey:
   bucketName:
   site:
   qiniu:
    accessKeyId:
    secretKey:
    bucketName:
  upload:
    path:
      root: ${pom.uploads.home}
  material:
    file:
       path: material