### Core \u8bbe\u7f6e
spring:
  main:
     banner-mode: "off"
  http:
    encoding:
     charset: UTF-8
     enabled: true
     force: true
  profiles:
   active: test
   include: shiro
  messages:
    encoding: UTF-8
  freemarker:
    prefix:
    suffix: .ftl
    templateLoaderPath: classpath:/templates/tpl/
    templateEncoding: UTF-8
    content-type: text/html
    prefer-file-system-access: false
    cache: false
    settings:
      template_update_delay: 0
      number_format: '0.##'   #数字格式化，无小数点
    request-context-attribute: request
info:
  app-name: lore
  app-description: ${info.app-name} 描述
  app-version: ${project.version}
#######maven pom \u91cc\u7684\u914d\u7f6e
server:
  port: 9080
management:
  endpoints:
    web:
      base-path: /admin/monitor
      exposure:
        exclude: ["env","beans" ,"shutdown" ]
        include: "*"
      path-mapping:
        health: healthcheck
  endpoint:
    logfile:
      enabled: true
    health:
      enabled: true
      ## 查看明细
      show-details: always